import Game from "../game";
import Gun from "../gun.js";
import Aim from "../aim.js";
import Bolt from "../bolt.js";
import Enemy from "../enemy.js";
import Star from "../star.js";
import Startup from "../startup";
import '../authentication/authentication.js';
import '../database/database.js';
import '../main.js';